//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtenFlow.IdentityServer.Domain.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExtenFlow.IdentityServer.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The client claim type is not defined..
        /// </summary>
        public static string ClientClaimTypeNotDefined
        {
            get
            {
                return ResourceManager.GetString("ClientClaimTypeNotDefined", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Concurrency check failure when updating the client in database. Expected stamp : &apos;{0}&apos;; Actual stamp : &apos;{1}&apos;..
        /// </summary>
        public static string ClientConcurrencyFailure
        {
            get
            {
                return ResourceManager.GetString("ClientConcurrencyFailure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The client concurrency stamp is not defined..
        /// </summary>
        public static string ClientConcurrencyStampNotDefined
        {
            get
            {
                return ResourceManager.GetString("ClientConcurrencyStampNotDefined", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The client id is not defined.
        /// </summary>
        public static string ClientIdNotDefined
        {
            get
            {
                return ResourceManager.GetString("ClientIdNotDefined", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The client name is not valid..
        /// </summary>
        public static string ClientNameInvalid
        {
            get
            {
                return ResourceManager.GetString("ClientNameInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The client name is not defined..
        /// </summary>
        public static string ClientNameNotDefined
        {
            get
            {
                return ResourceManager.GetString("ClientNameNotDefined", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Client with &apos;{0}&apos;=&apos;{1}&apos; not found..
        /// </summary>
        public static string ClientNotFound
        {
            get
            {
                return ResourceManager.GetString("ClientNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Client not initialized..
        /// </summary>
        public static string ClientNotInitialized
        {
            get
            {
                return ResourceManager.GetString("ClientNotInitialized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duplicate client with &apos;{0}&apos;=&apos;{1}&apos;..
        /// </summary>
        public static string DuplicateClient
        {
            get
            {
                return ResourceManager.GetString("DuplicateClient", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duplicate normalized client name. .
        /// </summary>
        public static string DuplicateNormalizedClientName
        {
            get
            {
                return ResourceManager.GetString("DuplicateNormalizedClientName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid client name : &apos;{0}&apos;..
        /// </summary>
        public static string InvalidClientName
        {
            get
            {
                return ResourceManager.GetString("InvalidClientName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid client normalized name : &apos;{0}&apos;..
        /// </summary>
        public static string InvalidClientNormalizedName
        {
            get
            {
                return ResourceManager.GetString("InvalidClientNormalizedName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Normalized.
        /// </summary>
        public static string Normalized
        {
            get
            {
                return ResourceManager.GetString("Normalized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The normalized client name is not defined..
        /// </summary>
        public static string NormalizedClientNameNotDefined
        {
            get
            {
                return ResourceManager.GetString("NormalizedClientNameNotDefined", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Normalized name.
        /// </summary>
        public static string NormalizedName
        {
            get
            {
                return ResourceManager.GetString("NormalizedName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The normalized name is used to find a client or to identify duplicate names. It&apos;s calculated by the system from the name..
        /// </summary>
        public static string NormalizedNameDescription
        {
            get
            {
                return ResourceManager.GetString("NormalizedNameDescription", resourceCulture);
            }
        }
    }
}
