//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtenFlow.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExtenFlow.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The aggregate identifier is not defined..
        /// </summary>
        public static string AggregateIdNotDefined {
            get {
                return ResourceManager.GetString("AggregateIdNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expected value for the aggregate type is &apos;%1&apos;. The actual type is &apos;%2&apos;..
        /// </summary>
        public static string AggregateTypeMismatch {
            get {
                return ResourceManager.GetString("AggregateTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The aggregate type is not defined..
        /// </summary>
        public static string AggregateTypeNotDefined {
            get {
                return ResourceManager.GetString("AggregateTypeNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The correlation identifier is not defined..
        /// </summary>
        public static string CorrelationIdNotDefined {
            get {
                return ResourceManager.GetString("CorrelationIdNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update of &apos;%1&apos; with &apos;%2&apos;=&apos;%3&apos; failed. It has been modified by another user. .
        /// </summary>
        public static string EntityConcurrencyCheckFailed {
            get {
                return ResourceManager.GetString("EntityConcurrencyCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;%1&apos; entity with key &apos;%2&apos;=&apos;%3&apos; was not found..
        /// </summary>
        public static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;%2&apos; property state is not initialized in &apos;%1&apos; entity..
        /// </summary>
        public static string EntityPropertyStateNotInitialized {
            get {
                return ResourceManager.GetString("EntityPropertyStateNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;%1&apos; entity state is not initialized..
        /// </summary>
        public static string EntityStateNotInitialized {
            get {
                return ResourceManager.GetString("EntityStateNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message identifier is not defined..
        /// </summary>
        public static string IdNotDefined {
            get {
                return ResourceManager.GetString("IdNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;%1&apos; is not a valid command for &apos;%2&apos;..
        /// </summary>
        public static string InvalidCommand {
            get {
                return ResourceManager.GetString("InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;%1&apos; is not a valid query for &apos;%2&apos;..
        /// </summary>
        public static string InvalidQuery {
            get {
                return ResourceManager.GetString("InvalidQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message creation date and time are not defined..
        /// </summary>
        public static string MessageDateTimeNotDefined {
            get {
                return ResourceManager.GetString("MessageDateTimeNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown object type..
        /// </summary>
        public static string UnkownType {
            get {
                return ResourceManager.GetString("UnkownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user identifier is not defined..
        /// </summary>
        public static string UserIdNotDefined {
            get {
                return ResourceManager.GetString("UserIdNotDefined", resourceCulture);
            }
        }
    }
}
