FROM mcr.microsoft.com/dotnet/core/sdk:3.1
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:5000
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 5000

WORKDIR /src
COPY ["src/Infrastructure/Identity/ExtenFlow.Identity.Abstractions/ExtenFlow.Identity.Abstractions.csproj", "src/Infrastructure/Identity/ExtenFlow.Identity.Abstractions/"]
COPY ["src/Infrastructure/Identity/ExtenFlow.Identity.Actors.Abstractions/ExtenFlow.Identity.Actors.Abstractions.csproj", "src/Infrastructure/Identity/ExtenFlow.Identity.Actors.Abstractions/"]
COPY ["src/Infrastructure/Identity/ExtenFlow.Identity.Actors/ExtenFlow.Identity.Actors.csproj", "src/Infrastructure/Identity/ExtenFlow.Identity.Actors/"]
COPY ["src/Infrastructure/Messages/ExtenFlow.Domain.Abstractions/ExtenFlow.Domain.Abstractions.csproj", "src/Infrastructure/Messages/ExtenFlow.Domain.Abstractions/"]
COPY ["src/Services/ExtenFlow.Identity.StoreActors/ExtenFlow.Identity.StoreActors.csproj", "src/Services/ExtenFlow.Identity.StoreActors/"]

RUN dotnet restore "src/Services/ExtenFlow.Identity.StoreActors/ExtenFlow.Identity.StoreActors.csproj"
COPY . .
WORKDIR "/src/src/Services/ExtenFlow.Identity.StoreActors"
RUN dotnet build --no-restore "ExtenFlow.Identity.StoreActors.csproj" -c $BUILD_CONFIGURATION

RUN echo "exec dotnet run --no-build --no-launch-profile -c $BUILD_CONFIGURATION --" > /entrypoint.sh

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]