//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtenFlow.Identity.IdentityServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExtenFlow.Identity.IdentityServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to your applications and resources, even when you are offline..
        /// </summary>
        internal static string AccessApplicationOffline {
            get {
                return ResourceManager.GetString("AccessApplicationOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No consent request matching request : %1.
        /// </summary>
        internal static string ConsentRequestMismatch {
            get {
                return ResourceManager.GetString("ConsentRequestMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External authentication error..
        /// </summary>
        internal static string ExternalAuthenticationError {
            get {
                return ResourceManager.GetString("ExternalAuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External claims: {%1}..
        /// </summary>
        internal static string ExternalClaimsLog {
            get {
                return ResourceManager.GetString("ExternalClaimsLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid client id : %1.
        /// </summary>
        internal static string InvalidClientId {
            get {
                return ResourceManager.GetString("InvalidClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login or password..
        /// </summary>
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid return URL..
        /// </summary>
        internal static string InvalidReturnUrl {
            get {
                return ResourceManager.GetString("InvalidReturnUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid selection..
        /// </summary>
        internal static string InvalidSelection {
            get {
                return ResourceManager.GetString("InvalidSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage is disabled in production. Returning 404..
        /// </summary>
        internal static string NoHomePageInProduction {
            get {
                return ResourceManager.GetString("NoHomePageInProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scopes matching: %1.
        /// </summary>
        internal static string NoScopeMatching {
            get {
                return ResourceManager.GetString("NoScopeMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline access..
        /// </summary>
        internal static string OfflineAccess {
            get {
                return ResourceManager.GetString("OfflineAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must pick at least one permission..
        /// </summary>
        internal static string PickOnePermission {
            get {
                return ResourceManager.GetString("PickOnePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The redirect URL is not defined..
        /// </summary>
        internal static string RedirectUrlNotDefined {
            get {
                return ResourceManager.GetString("RedirectUrlNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unkonwn user id..
        /// </summary>
        internal static string UnknownUserid {
            get {
                return ResourceManager.GetString("UnknownUserid", resourceCulture);
            }
        }
    }
}
