//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtenFlow.Actors.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExtenFlow.Actors.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actor state has not been initialized for actor {0} with Id &apos;{1}&apos;..
        /// </summary>
        public static string ActorStateNotInitialized {
            get {
                return ResourceManager.GetString("ActorStateNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actor type is not an interface..
        /// </summary>
        public static string ActorTypeNotInterface {
            get {
                return ResourceManager.GetString("ActorTypeNotInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &apos;{0}&apos; is null, empty or white spaces..
        /// </summary>
        public static string ArgumentIsNullEmptyOrWhiteSpace {
            get {
                return ResourceManager.GetString("ArgumentIsNullEmptyOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id is null, empty or white spaces..
        /// </summary>
        public static string IdIsNullEmptyOrWhiteSpace {
            get {
                return ResourceManager.GetString("IdIsNullEmptyOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with Id=&apos;{0}&apos; already exist in collection {1}..
        /// </summary>
        public static string ItemExistInCollection {
            get {
                return ResourceManager.GetString("ItemExistInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with Key=&apos;{0}&apos; already exist in unique index {1} with another Id=&apos;{2}&apos;..
        /// </summary>
        public static string ItemExistInIndex {
            get {
                return ResourceManager.GetString("ItemExistInIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message is not a command..
        /// </summary>
        public static string MessageNotCommand {
            get {
                return ResourceManager.GetString("MessageNotCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message is not a query..
        /// </summary>
        public static string MessageNotQuery {
            get {
                return ResourceManager.GetString("MessageNotQuery", resourceCulture);
            }
        }
    }
}
