//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtenFlow.Identity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExtenFlow.Identity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The claim type is not defined..
        /// </summary>
        public static string ClaimTypeNotDefined {
            get {
                return ResourceManager.GetString("ClaimTypeNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role &apos;{0}&apos; already exist..
        /// </summary>
        public static string DuplicateRole {
            get {
                return ResourceManager.GetString("DuplicateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Token : UserId=&apos;{0}&apos;; LoginProvider=&apos;{1}&apos;; TokenName=&apos;{2}&apos;.
        /// </summary>
        public static string DuplicateToken {
            get {
                return ResourceManager.GetString("DuplicateToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &apos;{0}&apos; already exist..
        /// </summary>
        public static string DuplicateUser {
            get {
                return ResourceManager.GetString("DuplicateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate user for login : UserIds=&apos;{0}/{3}&apos;; LoginProvider=&apos;{1}&apos;; ProviderKey=&apos;{2}&apos;..
        /// </summary>
        public static string DuplicateUserForLogin {
            get {
                return ResourceManager.GetString("DuplicateUserForLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate user login : UserId=&apos;{0}&apos;; LoginProvider=&apos;{1}&apos;; ProviderKey=&apos;{2}&apos;..
        /// </summary>
        public static string DuplicateUserLogin {
            get {
                return ResourceManager.GetString("DuplicateUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login provider is not defined..
        /// </summary>
        public static string LoginProviderNotDefined {
            get {
                return ResourceManager.GetString("LoginProviderNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login provider key is not defined..
        /// </summary>
        public static string ProviderKeyNotDefined {
            get {
                return ResourceManager.GetString("ProviderKeyNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role id is not defined.
        /// </summary>
        public static string RoleIdNotDefined {
            get {
                return ResourceManager.GetString("RoleIdNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role &apos;{0}&apos; not found..
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token not found : UserId=&apos;{0}&apos;; LoginProvider=&apos;{1}&apos;; TokenName=&apos;{2}&apos;.
        /// </summary>
        public static string TokenNotFound {
            get {
                return ResourceManager.GetString("TokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user id is not defined..
        /// </summary>
        public static string UserIdNotDefined {
            get {
                return ResourceManager.GetString("UserIdNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User login not found : UserId=&apos;{0}&apos;; LoginProvider=&apos;{1}&apos;; ProviderKey=&apos;{2}&apos;..
        /// </summary>
        public static string UserLoginNotFound {
            get {
                return ResourceManager.GetString("UserLoginNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
